### PR TITLE
Use config.json theme_version as global assets version (cache-buster)

### PR DESCRIPTION
**Pull request by brandomeniconi**
#### Changes proposed in this Pull Request:
Use `theme_version` in  `config.json` as global assets variable. This  allows CSS, JS, etc changes to be deployed with more ease.

```json
{
    "theme_version": "2.0.0",
}
```

Produces
```
dist/css/common.css?ver=2.0.0
dist/css/single-post.css?ver=2.0.0
...
```

Now every time we made a change in assets we must remember to update the _version_ in `config.json` before deployment.

### CODE REVIEW

**Comment by brandomeniconi** [comment]
@CostyEffe do you update often icons fonts? Because if you do so we also need to parametrize this file:
https://github.com/silverbackstudio/_svbk/blob/a5c299d44958dbeae546e220f3b2c981c927a487/style/icons/style.css#L3

Probably we need to move the icons font-embedding code in a `sass` file into typography folder to use variables?

**Comment by CostyEffe** [comment]
> @CostyEffe do you update often icons fonts? Because if you do so we also need to parametrize this file:
> https://github.com/silverbackstudio/_svbk/blob/a5c299d44958dbeae546e220f3b2c981c927a487/style/icons/style.css#L3
> 
> Probably we need to move the icons font-embedding code in a `sass` file into typography folder to use variables?

I do update the icons set quite often for custom projects. Not that frequently - almost never, I'd dare say - with standard projects mostly based on the svbk model.

Anyway, as long as we agree there's nothing wrong updating the file version parameter over and over without really changing the file content, I've really nothing to object.

I just take the chance to share an issue I'm having retrieving the `theme_version` value with sass.
The variable interpolation has an unexpected output, so that `2.0.0` returns a `2 0` string. I'm on it. 

Meantime, **you can surely parametrize the file you pointed out**.

**Comment by brandomeniconi** [comment]
Ok I also got the interpolation error, there is no easy fix on that, The only way is to do a pull request to the [pmowrer/node-sass-json-importer](https://github.com/pmowrer/node-sass-json-importer) or replace the library with the [sasstools/json-importer](https://github.com/sasstools/json-importer) which treat all values as strings. The latter require to update all variable in CSS.

Otherwise if  we update it very often maybe we can simply update the version manually like so:
```css
src: url('fonts/theme-icons.woff?v=x.x.x') format('woff'), 
```

**Comment by CostyEffe** [comment]
> Otherwise if we update it very often maybe we can simply update the version manually like so:
> 
> ```css
> src: url('fonts/theme-icons.woff?v=x.x.x') format('woff'), 
> ```

Not that big a deal. Plainly said, building the icons set at once would assume a smoother workflow. It should probably work like that.

The main side effect consists in weighing down the cognitive burden during tasks such as deployment and update. It's maybe just a matter of writing out all the necessary actions and precautions to handle them in the best way. But this is probably an off-thread. :grimacing:

**Pull request merged**
